name: Create Release

on:
  workflow_dispatch:

env:
  BUILD_TYPE: MinSizeRel
  BANG_SDL_REPO_NAME: ${{ vars.BANG_SDL_REPO_NAME }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake

    - name: Configure CMake
      shell: msys2 {0}
      working-directory: ${{github.workspace}}
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_CXX_COMPILER=g++
        -DBANG_SDL_REPO_NAME=${{env.BANG_SDL_REPO_NAME}}
      
    - name: Build
      shell: msys2 {0}
      working-directory: ${{github.workspace}}
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v4
      with:
        name: banglauncher
        path: build/banglauncher.exe